/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ProcessInformation */

#ifndef _Included_ProcessInformation
#define _Included_ProcessInformation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ProcessInformation
 * Method:    getProcessCPUTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ProcessInformation_getProcessCPUTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
